name: Node.js CI - with cache - composite

on:
  workflow_dispatch:
  push:

jobs:
  ci: 
    name: run build process
    uses: cometbid-sfi/GHA.workflows/.github/workflows/gha.workflows.build-node-composite.yml@main

