name: Node.js CI - with cache and artefact upload

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Restore Cache
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        
    - name: Install dependencies
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
    
    - name: Save npm cache
      if: steps.cache-npm.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app
        path: |
          dist/
          build/
          !dist/**/*.md
          !build/**/*.md
          retention-days: 5