name: Dev Deployment

on:
  push:
    branches:
      - ci/feature  

jobs:  
  dev-job:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ vars.ENV_VAL }}"  >> $GITHUB_STEP_SUMMARY